chain:
  gap_extend: 2.0        # INCREASED: Higher gap extension penalty
  gap_open: 5.0          # INCREASED: Higher gap opening penalty  
  offset_band: 1         # DECREASED: Tight positional constraints
  slope_penalty: 0.2     # INCREASED: Higher slope penalty
continuous:
  hnsw_enable: false
  srp_bits: 256
  srp_seed: 13
data:
  allow_overwrite: false
  work_dir: ./elsa_index
discrete:
  K: 4096
  bands_rows:
  - 24
  - 8
  emit_skipgram: true
  idf_max_df_frac: 0.05
  idf_min_df: 5
  minhash_hashes: 192
dtw:
  band: 1                # CONSTRAINED: Very tight DTW band
  enable: false          # DISABLED: No DTW for cassette mode
ingest:
  gene_caller: prodigal
  keep_partial: false
  min_cds_aa: 60
  prodigal_mode: single
plm:
  batch_amino_acids: 16000
  device: auto
  fp16: true
  l2_normalize: true
  model: esm2_t12
  project_to_D: 256
score:
  alpha: 1.0
  beta: 0.1
  delta: 0.1
  fdr_target: 0.01
  gamma: 0.2
shingles:
  n: 2                   # REDUCED: 2-gene shingles for fine resolution
  pos_dim: 16
  strand_flag: signed
  stride: 1
  weights: triangular

# Multi-scale windowing configuration
window:
  micro:
    size: 2              # REDUCED: 2 genes per micro window  
    stride: 1
  macro:
    size: 4              # Small macro windows if needed
    stride: 2
  adaptive:
    enable: false        # Keep simple for cassettes

# Phase-2 Feature Flags - DISABLE MACRO WINDOWS
phase2:
  enable: true
  weighted_sketch: true
  multiscale: false      # DISABLED: No macro windows for cassettes
  flip_dp: false
  calibration: true      # Enable FDR control
  hnsw: false

# Cassette mode configuration
cassette_mode:
  enable: true           # ENABLED: Use cassette mode for smaller blocks
  anchors:
    cosine_min: 0.91     # High cosine similarity threshold
    jaccard_min: 0.30    # Jaccard similarity threshold
    reciprocal_topk: 2   # Mutual top-k filtering
    blacklist_top_pct: 1.0  # Blacklist top collision windows
    lambda_jaccard: 0.5  # Jaccard weight in chain scoring
  chain:
    delta_min: 0.02      # Minimum local gain per step
    density_window_genes: 10    # Window for density calculation
    density_min_anchors_per_gene: 0.3  # Min anchor density
    pos_band_genes: 1    # Position drift tolerance
    max_gap_genes: 1     # Maximum gap size
  segmenter:
    method: chain        # Use improved chaining (vs ransac)

system:
  jobs: auto
  mmap: true
  rng_seed: 17

analyze:
  clustering:
    method: mutual_jaccard
    sink_label: 0
    keep_singletons: false

    # Robustness gate
    min_anchors: 4
    min_span_genes: 8
    v_mad_max_genes: 1

    # SRP shingling
    srp_bits: 256
    srp_bands: 32
    srp_band_bits: 8
    srp_seed: 1337
    shingle_k: 3
    shingle_method: xor

    # Graph construction (XOR path)
    jaccard_tau: 0.5
    mutual_k: 3
    df_max: 200

    # Hybrid bandset augmentation
    enable_hybrid_bandset: true
    bandset_tau: 0.25
    bandset_df_max: 3000
    bandset_min_len: 20
    bandset_min_identity: 0.98
    
    # Candidate pruning (hybrid_mid default)
    enable_mutual_topk_filter: false
    max_candidates_per_block: 2000
    min_shared_shingles: 2
    bandset_topk_candidates: 500
    min_shared_band_tokens: 2
