chain:
  gap_extend: 1.5          # *** INCREASED: Higher gap extension penalty ***
  gap_open: 4.0            # *** INCREASED: Higher gap opening penalty ***
  offset_band: 3           # *** DECREASED: Tighter positional constraints ***
  slope_penalty: 0.1       # *** INCREASED: Higher slope penalty ***
  # Phase-2 chaining parameters - MORE RESTRICTIVE
  alpha: 0.5               # *** INCREASED: Higher position deviation penalty ***
  beta: 2.0                # *** INCREASED: Higher gap penalty ***
  gamma: 3.0               # *** INCREASED: Higher strand flip penalty ***
  # NEW: Chain length limits for small cassettes
  max_chain_length: 8      # *** NEW: Maximum 8 windows (24 genes max) ***
  min_chain_length: 2      # *** NEW: Minimum 2 windows (6 genes min) ***
continuous:
  hnsw_enable: true
  srp_bits: 256
  srp_seed: 13
data:
  allow_overwrite: false
  work_dir: ./elsa_index
discrete:
  K: 4096
  bands_rows:
  - 24
  - 8
  emit_skipgram: true
  idf_max_df_frac: 0.05
  idf_min_df: 5
  minhash_hashes: 192
dtw:
  band: 10
  enable: true
  # Phase-2 DTW refinement  
  refine_enable: true            # bounded DTW on final chain only
  refine_band: 2                  # DTW band width in genes
ingest:
  gene_caller: prodigal
  keep_partial: false
  min_cds_aa: 60
  prodigal_mode: single
plm:
  batch_amino_acids: 16000
  device: auto
  fp16: true
  l2_normalize: true
  model: esm2_t12
  project_to_D: 256
score:
  alpha: 1.0
  beta: 0.1
  delta: 0.1
  fdr_target: 0.01
  gamma: 0.2
shingles:
  n: 3                   # *** REDUCED: 3-gene shingles for finer resolution ***
  pos_dim: 16
  strand_flag: signed
  stride: 1
  weights: triangular
system:
  jobs: auto
  mmap: true
  rng_seed: 17

# Phase-2 Feature Flags and Configuration
phase2:
  enable: true                    # Master switch for all Phase-2 features
  weighted_sketch: true          # Use weighted MinHash with IDF weighting
  multiscale: false               # *** DISABLED: No macro windows for small cassettes ***
  flip_dp: false                  # Use flip-aware affine-gap chaining
  calibration: true               # Enable null models and FDR control
  hnsw: false                     # Use HNSW dense retrieval

# Weighted sketching configuration
sketch:
  type: "weighted_minhash"                 # "minhash" or "weighted_minhash"
  bits: 64                        # 64, 2, or 1 for compression
  size: 96                        # sketch size
  idf:
    max: 10.0                     # clamp IDF values
  
# Note: MGE masking has been removed from Phase-2

# Micro-only windowing (macro disabled)
window:
  micro:
    size: 3              # *** REDUCED: 3 genes per micro window ***
    stride: 1
  # macro: REMOVED - multiscale disabled above
  adaptive:
    enable: false        # *** DISABLED: Keep simple for cassettes ***

# HNSW configuration
hnsw:
  M: 16
  efConstruction: 200
  efSearch: 50

# Retrieval method selection
retrieval:
  dense: "srp"                    # "srp" or "hnsw"

# Calibration parameters
calib:
  null:
    iters: 100                    # null model iterations
  target_fdr: 0.05                # FDR threshold