
continuous:
  srp_bits: 256
  srp_seed: 13
data:
  allow_overwrite: false
  work_dir: ./elsa_index
discrete:
  K: 4096
  bands_rows: [24, 8]
  emit_skipgram: true
  minhash_hashes: 192
ingest:
  gene_caller: prodigal
  keep_partial: false
  min_cds_aa: 60
  prodigal_mode: single
plm:
  batch_amino_acids: 16000
  device: auto
  fp16: true
  l2_normalize: true
  model: esm2_t12
  project_to_D: 256
score:
  alpha: 1.0
  beta: 0.1
  delta: 0.1
  fdr_target: 0.01
  gamma: 0.2
shingles:
  n: 2
  pos_dim: 16
  strand_flag: signed
  stride: 1
  weights: triangular
cassette_mode:
  enable: true
  anchors: { cosine_min: 0.91, jaccard_min: 0.3, reciprocal_topk: 2, blacklist_top_pct: 1.0, lambda_jaccard: 0.5 }
  chain: { delta_min: 0.02, density_window_genes: 10, density_min_anchors_per_gene: 0.3, pos_band_genes: 1, max_gap_genes: 1 }
  segmenter: { method: chain }
system:
  jobs: auto
  rng_seed: 17
analyze:
  clustering:
    method: mutual_jaccard
    sink_label: 0
    keep_singletons: false
    min_anchors: 5
    min_span_genes: 10
    v_mad_max_genes: 1
    srp_bits: 256
    srp_bands: 32
    srp_band_bits: 8
    srp_seed: 1337
    shingle_k: 3
    shingle_method: xor
    ignore_strand_in_tokens: true
    strand_canonical_shingles: true
    shingle_pattern: [0, 2, 5]
    jaccard_tau: 0.5
    df_max: 200
    max_candidates_per_block: 100000
    min_shared_shingles: 1

  attach:
    enable: true
    member_sample: 5
    k1_method: xor
    icws_r: 8
    icws_bbit: 0
    enable_stitch: true
    stitch_gap: 2
    stitch_max_neighbors: 2
    bandset_contain_tau: 0.65
    k1_contain_tau: 0.65
    k1_inter_min: 2
    margin_min: 0.10
    triangle_min: 1
    triangle_member_tau: 0.50
    tiny_window_cap: 3
    bandset_contain_tau_tiny: 0.55
    k1_contain_tau_tiny: 0.55
    k1_inter_min_tiny: 1
    margin_min_tiny: 0.05
    triangle_min_tiny: 1
    triangle_member_tau_tiny: 0.50
