# ELSA Configuration - Corrected for Two-Level Windowing
# This addresses the whole-contig alignment issue by adding coordinate-based windowing

chain:
  gap_extend: 0.5
  gap_open: 2.0
  offset_band: 10
  slope_penalty: 0.05

continuous:
  hnsw_enable: false
  srp_bits: 256
  srp_seed: 13

data:
  allow_overwrite: false
  work_dir: ./elsa_index_corrected

discrete:
  K: 4096
  bands_rows:
  - 24
  - 8
  emit_skipgram: true
  idf_max_df_frac: 0.05
  idf_min_df: 5
  minhash_hashes: 192

dtw:
  band: 10
  enable: true

ingest:
  gene_caller: prodigal
  keep_partial: false
  min_cds_aa: 60
  prodigal_mode: single

plm:
  batch_amino_acids: 16000
  device: auto
  fp16: true
  l2_normalize: true
  model: esm2_t12
  project_to_D: 256

score:
  alpha: 1.0
  beta: 0.1
  delta: 0.1
  fdr_target: 0.01
  gamma: 0.2

# CRITICAL FIX: Add coordinate-based windowing before gene shingling
windowing:
  enable: true                    # Enable two-level windowing
  window_size: 15000             # 15kb genomic windows (good for operons/gene clusters)
  window_stride: 7500            # 50% overlap to catch boundary-spanning synteny
  min_genes_per_window: 3        # Require at least 3 genes per window
  max_genes_per_window: 50       # Cap for performance (very dense regions)

shingles:
  n: 5                           # 5 consecutive genes per shingle (unchanged)
  pos_dim: 16                    # Positional encoding dimension (unchanged)
  strand_flag: signed            # Include strand information (unchanged) 
  stride: 1                      # Move 1 gene at a time within windows (unchanged)
  weights: triangular            # Weight center genes more heavily (unchanged)

system:
  jobs: auto
  mmap: true
  rng_seed: 17