analyze:
  clustering:
    method: mutual_jaccard
    sink_label: 0
    keep_singletons: false
    min_anchors: 4
    min_span_genes: 8
    v_mad_max_genes: 1
    # SRP: more bands (64x4) still 256 bits total
    srp_bits: 256
    srp_bands: 64
    srp_band_bits: 4
    srp_seed: 1337
    shingle_k: 3
    shingle_method: xor
    strand_canonical_shingles: true
    jaccard_tau: 0.5
    mutual_k: 3
    df_max: 200
    enable_hybrid_bandset: false
    bandset_tau: 0.25
    bandset_df_max: 3000
    bandset_min_len: 20
    bandset_min_identity: 0.98
    enable_mutual_topk_filter: false
    max_candidates_per_block: 100000
    min_shared_shingles: 1
    bandset_topk_candidates: 100000
    min_shared_band_tokens: 1

