analyze:
  clustering:
    method: mutual_jaccard
    sink_label: 0
    keep_singletons: false

    # Robustness gate (keep default-ish)
    min_anchors: 4
    min_span_genes: 8
    v_mad_max_genes: 1

    # SRP shingling
    srp_bits: 256
    srp_bands: 32
    srp_band_bits: 8
    srp_seed: 1337
    shingle_k: 3
    shingle_method: xor

    # Graph construction (XOR path)
    jaccard_tau: 0.5
    mutual_k: 3
    df_max: 200

    # Hybrid disabled for control
    enable_hybrid_bandset: false
    bandset_tau: 0.25
    bandset_df_max: 3000
    bandset_min_len: 20
    bandset_min_identity: 0.98

    # Pruning defaults (more permissive than tight caps)
    enable_mutual_topk_filter: false
    max_candidates_per_block: 100000
    min_shared_shingles: 1
    bandset_topk_candidates: 100000
    min_shared_band_tokens: 1

  attach:
    enable: true
    # Method
    member_sample: 5
    k1_method: xor
    icws_r: 8
    icws_bbit: 0
    # Stitching
    enable_stitch: true
    stitch_gap: 2
    stitch_max_neighbors: 2
    # Main thresholds (kept strict)
    bandset_contain_tau: 0.65
    k1_contain_tau: 0.65
    k1_inter_min: 2
    margin_min: 0.10
    triangle_min: 1
    triangle_member_tau: 0.50
    # Tiny-block relax (exp8-like)
    tiny_window_cap: 3
    bandset_contain_tau_tiny: 0.55
    k1_contain_tau_tiny: 0.55
    k1_inter_min_tiny: 1
    margin_min_tiny: 0.05
    triangle_min_tiny: 1
    triangle_member_tau_tiny: 0.50

