chain:
  gap_extend: 2.0
  gap_open: 5.0
  offset_band: 1
  slope_penalty: 0.2
continuous:
  hnsw_enable: false
  srp_bits: 256
  srp_seed: 13
data:
  allow_overwrite: false
  work_dir: ./elsa_index
discrete:
  K: 4096
  bands_rows:
  - 24
  - 8
  emit_skipgram: true
  idf_max_df_frac: 0.05
  idf_min_df: 5
  minhash_hashes: 192
dtw:
  band: 1
  enable: false
ingest:
  gene_caller: prodigal
  keep_partial: false
  min_cds_aa: 60
  prodigal_mode: single
plm:
  batch_amino_acids: 16000
  device: auto
  fp16: true
  l2_normalize: true
  model: esm2_t12
  project_to_D: 256
score:
  alpha: 1.0
  beta: 0.1
  delta: 0.1
  fdr_target: 0.01
  gamma: 0.2
shingles:
  n: 2
  pos_dim: 16
  strand_flag: signed
  stride: 1
  weights: triangular
window:
  micro:
    size: 2
    stride: 1
  macro:
    size: 4
    stride: 2
  adaptive:
    enable: false
phase2:
  enable: true
  weighted_sketch: true
  multiscale: false
  flip_dp: false
  calibration: true
  hnsw: false
cassette_mode:
  enable: true
  anchors:
    cosine_min: 0.91
    jaccard_min: 0.3
    reciprocal_topk: 2
    blacklist_top_pct: 1.0
    lambda_jaccard: 0.5
  chain:
    delta_min: 0.02
    density_window_genes: 10
    density_min_anchors_per_gene: 0.3
    pos_band_genes: 1
    max_gap_genes: 1
  segmenter:
    method: chain
system:
  jobs: auto
  mmap: true
  rng_seed: 17
analyze:
  clustering:
    method: mutual_jaccard
    sink_label: 0
    keep_singletons: false
    min_anchors: 5
    min_span_genes: 10
    v_mad_max_genes: 1
    srp_bits: 256
    srp_bands: 32
    srp_band_bits: 8
    srp_seed: 1337
    shingle_k: 3
    shingle_method: xor
    strand_canonical_shingles: true
    jaccard_tau: 0.5
    mutual_k: 3
    df_max: 200
    enable_hybrid_bandset: false
    bandset_tau: 0.25
    bandset_df_max: 3000
    bandset_min_len: 20
    bandset_min_identity: 0.98
    enable_mutual_topk_filter: false
    max_candidates_per_block: 100000
    min_shared_shingles: 1
    bandset_topk_candidates: 100000
    min_shared_band_tokens: 1

  attach:
    enable: true
    member_sample: 5
    k1_method: xor
    icws_r: 8
    icws_bbit: 0
    enable_stitch: true
    stitch_gap: 2
    stitch_max_neighbors: 2
    bandset_contain_tau: 0.65
    k1_contain_tau: 0.65
    k1_inter_min: 2
    margin_min: 0.10
    triangle_min: 1
    triangle_member_tau: 0.50
    tiny_window_cap: 3
    bandset_contain_tau_tiny: 0.55
    k1_contain_tau_tiny: 0.55
    k1_inter_min_tiny: 1
    margin_min_tiny: 0.05
    triangle_min_tiny: 1
    triangle_member_tau_tiny: 0.50

