analyze:
  clustering:
    method: mutual_jaccard
    sink_label: 0
    keep_singletons: false

    # Robustness gate (same as control)
    min_anchors: 4
    min_span_genes: 8
    v_mad_max_genes: 1

    # SRP tokenization
    srp_bits: 256
    srp_bands: 32
    srp_band_bits: 8
    srp_seed: 1337

    # ICWS window sketch + skip-grams
    shingle_method: icws
    shingle_k: 3              # used for contiguous mode; skip-gram uses offsets
    shingle_pattern: "0,2,5"  # enable 3-offset skip-grams for robustness
    icws_r: 8                 # ICWS samples per window (tuple length)
    icws_bbit: 0              # keep native ids (no b-bit packing)
    strand_canonical_shingles: true  # orientation-invariant shingles

    # Graph construction (match control)
    jaccard_tau: 0.5
    mutual_k: 3
    df_max: 200

    # Hybrid disabled (ICWS-only)
    enable_hybrid_bandset: false
    bandset_tau: 0.25
    bandset_df_max: 3000
    bandset_min_len: 20
    bandset_min_identity: 0.98

    # Candidate/pruning caps (match control, permissive)
    enable_mutual_topk_filter: false
    max_candidates_per_block: 100000
    min_shared_shingles: 1
    bandset_topk_candidates: 100000
    min_shared_band_tokens: 1
