analyze:
  clustering:
    method: mutual_jaccard
    sink_label: 0
    keep_singletons: false

    # Robustness gate
    min_anchors: 4
    min_span_genes: 8
    v_mad_max_genes: 1

    # SRP shingling (non-hybrid baseline)
    srp_bits: 256
    srp_bands: 32
    srp_band_bits: 8
    srp_seed: 1337
    shingle_k: 3
    shingle_method: xor

    # Graph construction (non-hybrid XOR path)
    jaccard_tau: 0.5
    mutual_k: 3
    df_max: 200

    # Hybrid disabled (stay non-hybrid globally)
    enable_hybrid_bandset: false
    bandset_tau: 0.25           # ignored when hybrid disabled
    bandset_df_max: 3000        # ignored when hybrid disabled
    bandset_min_len: 20         # ignored when hybrid disabled
    bandset_min_identity: 0.98  # ignored when hybrid disabled

    # Targeted bandset acceptor (narrow, long+high-identity only)
    enable_targeted_bandset_acceptor: true
    targeted_bandset_tau: 0.25
    targeted_bandset_df_max: 2000
    targeted_bandset_min_len: 20
    targeted_bandset_min_identity: 0.98

    # Candidate pruning (compact but allow bandset to propose)
    enable_mutual_topk_filter: true
    max_candidates_per_block: 1000
    min_shared_shingles: 2
    bandset_topk_candidates: 100
    min_shared_band_tokens: 9
    degree_cap: 8

